package org.apache.zookeeper;

import static org.junit.Assert.assertEquals;

import java.util.Random;

import org.junit.Test;

public class JitteredExponentialBackoffRetrierTest {

    @Test
    public void testGetJitteredWaitMs() {
        // Provide random number generator with a deterministic seed
        int seed = 0;
        Random random = new Random(seed);

        // A retrier starting with 1ms with exponent base 2, up to 10ms.
        Retrier r = new JitteredExponentialBackoffRetrier(1, 10, 2, new Random(seed));

        // The jittered value is generated by multiplying the underlying exponential
        // series by a random value in the interval [0, 1).
        double randomDouble = random.nextDouble();
        assertEquals((long) randomDouble * 1, r.getNextWaitMs());

        randomDouble = random.nextDouble();
        assertEquals((long) randomDouble * 2, r.getNextWaitMs());

        randomDouble = random.nextDouble();
        assertEquals((long) randomDouble * 4, r.getNextWaitMs());
    }
}
